apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "textStatService.fullname" . }}
  labels:
    app: {{ template "textStatService.name" . }}
    chart: {{ template "textStatService.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
      annotations:
{{ toYaml .Values.server.podAnnotations | indent 8 }}
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: {{ template "textStatService.fullname" . }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.imagePullPolicy }}
          # enableServiceLinks: false
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.service.internalPort }}
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
    {{- if .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 8 }}
    {{- end }}